CREATE TABLE Metric.Run
	(
		RunId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
		StartDT DateTime NOT NULL DEFAULT(GETDATE()),
		EndDT DateTime NULL,
		RunTitle VARCHAR(200) NOT NULL,
		RunNotes VARCHAR(max) NULL
	)